[package]
license.workspace = true
name = "mo-unicode"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
schemars.workspace = true
thiserror.workspace = true
unicode-bidi.workspace = true

[lints]
workspace = true
