//! Only failure transport probes use scripts. Positive output is generated by
//! the actual native renderer, never a fabricated successful preview.
use super::*;
use mo_native_export::{NativeExporter, executable_digest};
use serde_json::json;
use std::{
    os::unix::fs::PermissionsExt,
    process::{Command, Stdio},
    time::{Duration, Instant},
};

fn script(root: &Root, name: &str, text: &str, timeout: Duration) -> NativeExporter {
    let path = root.path().join(name);
    fs::write(&path, format!("#!/bin/sh\n{text}\n")).unwrap();
    fs::set_permissions(&path, fs::Permissions::from_mode(0o700)).unwrap();
    NativeExporter::new(
        path.clone(),
        executable_digest(&path).unwrap(),
        root.spool(),
        timeout,
    )
    .unwrap()
}

#[test]
fn killed_or_timed_out_worker_is_reaped_before_its_orphans_are_removed() {
    for cancel in [false, true] {
        let root = Root::new();
        // Allow process startup on a loaded development machine. The timeout
        // assertion still requires a real live child and an observed orphan.
        let timeout = Duration::from_secs(if cancel { 10 } else { 3 });
        let exporter = script(
            &root,
            "blocked",
            r#"/bin/mkdir "$2/abandoned"
printf orphan > "$2/abandoned/output"
printf '%s' "$$" > "${0}.pid"
exec /bin/sleep 30"#,
            timeout,
        );
        let (snapshot, request, assets) = input(exporter.renderer_identity());
        let pid_file = root.path().join("blocked.pid");
        let before = Instant::now();
        let error = exporter
            .prepare(&request, snapshot, &assets, &|| {
                cancel && fs::read_to_string(&pid_file).is_ok_and(|p| p.parse::<u32>().is_ok())
            })
            .err()
            .unwrap();
        assert_eq!(
            error.code,
            if cancel {
                FailureCode::Cancelled
            } else {
                FailureCode::ExecutionInterrupted
            }
        );
        assert!(before.elapsed() < Duration::from_secs(8), "{error:?}");
        if !cancel {
            assert!(error.message.contains("timed out"), "{error:?}");
            assert!(before.elapsed() >= timeout);
        }
        let pid = fs::read_to_string(pid_file).unwrap();
        assert!(pid.parse::<u32>().unwrap() > 1);
        assert!(
            !Command::new("/bin/kill")
                .args(["-0", pid.trim()])
                .stderr(Stdio::null())
                .status()
                .unwrap()
                .success()
        );
        root.clean();
    }
}

#[test]
fn changed_operator_executable_is_rejected_before_execution() {
    let root = Root::new();
    let exporter = script(&root, "changed", "exit 0", Duration::from_secs(3));
    let (snapshot, request, assets) = input(exporter.renderer_identity());
    fs::write(root.path().join("changed"), b"#!/bin/sh\nexit 2\n").unwrap();
    assert_eq!(
        exporter
            .prepare(&request, snapshot, &assets, &|| false)
            .err()
            .unwrap()
            .code,
        FailureCode::ExecutorMismatch
    );
    root.clean();
}

#[test]
fn forged_pins_corrupted_or_truncated_bytes_and_failed_exit_are_rejected() {
    let original = Root::new();
    let exporter = exporter(&original);
    let (snapshot, request, assets) = input(exporter.renderer_identity());
    let candidate = exporter
        .prepare(&request, snapshot, &assets, &|| false)
        .unwrap();
    let payload: Vec<u8> = candidate
        .assets()
        .iter()
        .flat_map(|asset| bytes(&candidate, &asset.id))
        .collect();
    for fault in 0..8 {
        let root = Root::new();
        let code = if fault == 7 {
            "/bin/cat > /dev/null\n/bin/cat \"${0}.response\"\nexit 9"
        } else {
            "/bin/cat > /dev/null\nexec /bin/cat \"${0}.response\""
        };
        let replay = script(&root, "replay", code, Duration::from_secs(10));
        let (snapshot, request, assets) = input(replay.renderer_identity());
        let mut header = json!({"status": "prepared", "requestDigest": request.digest().unwrap(), "receipt": candidate.receipt()});
        let mut body = payload.clone();
        match fault {
            0 => header["requestDigest"] = json!(Digest::from_sha256([0; 32])),
            1 => header["receipt"]["semanticDigest"] = json!(Digest::from_sha256([0; 32])),
            2 => body[0] ^= 1,
            3 => {
                body.pop();
            }
            4 => {
                body.push(1);
            }
            5 => {
                header["receipt"]["bundle"]["assets"][1] =
                    header["receipt"]["bundle"]["assets"][0].clone();
                body.clear();
            }
            6 | 7 => (), // unmodified files must still reject a different renderer / bad exit
            _ => unreachable!(),
        }
        let json = serde_json::to_vec(&header).unwrap();
        let mut frame = (json.len() as u32).to_le_bytes().to_vec();
        frame.extend(json);
        frame.extend(body);
        fs::write(root.path().join("replay.response"), frame).unwrap();
        let error = replay
            .prepare(&request, snapshot, &assets, &|| false)
            .err()
            .unwrap();
        let expected = match fault {
            0 | 1 => FailureCode::ResultMismatch,
            4 | 7 => FailureCode::ExecutionInterrupted,
            _ => FailureCode::InputInvalid,
        };
        assert_eq!(error.code, expected, "fault {fault}: {error:?}");
        if fault == 2 {
            assert!(
                error.message.contains("actual delivery bytes differ"),
                "{error:?}"
            );
        }
        if fault == 6 {
            assert!(error.message.contains("context"), "{error:?}");
        }
        root.clean();
    }
    drop(candidate);
    original.clean();
}
