[package]
name = "mo-wasm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
mo-presentation-template.workspace = true
serde_json.workspace = true
mo-image.workspace = true
mo-kernel-api.workspace = true
mo-presentation-operations.workspace = true
mo-text.workspace = true
mo-raster.workspace = true
wasm-bindgen.workspace = true

[lints]
workspace = true
