[package]
name = "mo-embedded-sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
sha2.workspace = true
mo-common.workspace = true
mo-native-export.workspace = true
mo-native-io.workspace = true
mo-presentation-operations.workspace = true
mo-opc.workspace = true
mo-presentation-delivery.workspace = true
mo-presentation-edit.workspace = true
mo-presentation-model.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
