[package]
name = "mo-native-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
[dependencies]
mo-native-worker.workspace = true
mo-kernel-api.workspace = true
mo-timeline.workspace = true
thiserror.workspace = true
mo-presentation-delivery.workspace = true
mo-presentation-compile.workspace = true
mo-common.workspace = true
mo-raster.workspace = true
serde_json.workspace = true
serde.workspace = true
sha2.workspace = true
[dev-dependencies]
mo-native-io.workspace = true
mo-opc.workspace = true
mo-pptx.workspace = true
mo-presentation-edit.workspace = true
mo-presentation-model.workspace = true
[lints]
workspace = true
