[package]
name = "mo-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
mo-kernel-api.workspace = true
mo-opc.workspace = true
mo-common.workspace = true
mo-raster.workspace = true
mo-native-io.workspace = true
mo-native-worker.workspace = true
sha2.workspace = true
rawzip.workspace = true
serde_json.workspace = true

[lints]
workspace = true
