[package]
name = "mo-raster-worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
[dependencies]
mo-image.workspace = true
mo-kernel-api.workspace = true
mo-skia-sys.workspace = true
mo-raster.workspace = true
mo-harfbuzz-sys.workspace = true
[lints]
workspace = true
