[package]
name = "mo-harfbuzz-sys"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
links = "mo_harfbuzz"

[dependencies]
mo-text.workspace = true

[build-dependencies]
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
mo-presentation-model.workspace = true
mo-image.workspace = true
mo-common.workspace = true
mo-geometry.workspace = true
mo-opc.workspace = true
mo-pptx.workspace = true
mo-presentation-compile.workspace = true
mo-raster.workspace = true
mo-skia-sys.workspace = true
serde_json.workspace = true

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
all = { level = "warn", priority = -1 }
