"""Measure saved native WPS captures and LibreOffice PDFs of owned test pages.

The window captures contain unrelated application chrome and remain private in
.codex-work. Only geometry from the explicitly inspected slide canvas is emitted.
This is a coarse geometric observation, not a pixel/round-trip acceptance gate.
Run in the development Python with Pillow, NumPy and PyMuPDF.
"""
import hashlib
import json
import math
import plistlib
import sys
from pathlib import Path

import fitz
import numpy as np
from PIL import Image

ROOT = Path(sys.argv[1] if len(sys.argv)>1 else '.codex-work/group-compat')
U = 1 << 32


def read(path):
    return json.loads(Path(path).read_text())


def entry(path):
    p = Path(path)
    data = p.read_bytes()
    return {'path': str(p), 'byteLength': len(data), 'sha256': hashlib.sha256(data).hexdigest()}


def distance(point, a, b):
    dx, dy = b[0]-a[0], b[1]-a[1]
    norm = dx*dx+dy*dy
    t = max(0, min(1, ((point[0]-a[0])*dx+(point[1]-a[1])*dy)/norm)) if norm else 0
    return math.hypot(point[0]-a[0]-t*dx, point[1]-a[1]-t*dy)


def to_edge(point, polygon):
    return min(distance(point, a, b) for a, b in zip(polygon, polygon[1:]+polygon[:1]))


def expected_vertices(result, document, object_id):
    p = next(p for p in result['surfaces'][0]['objects'] if p['object'] == object_id)
    commands = document['objects'][object_id]['content']['geometry']['commands']
    assert [c['kind'] for c in commands] == ['move', 'line', 'line', 'line', 'close']
    anchor = [int(p['anchor'][a])/U for a in ['x', 'y']]
    matrix = [int(v)/U for v in p['affine']['linear']]
    center = [int(p['affine']['translation'][a])/U for a in ['x', 'y']]
    vertices = []
    for command in commands[:-1]:
        x, y = [int(command['to'][a])-anchor[i] for i, a in enumerate(['x', 'y'])]
        vertices.append([(matrix[0]*x+matrix[1]*y+center[0])/9525,
                         (matrix[2]*x+matrix[3]*y+center[1])/9525])
    return vertices


def registration(image):
    # These four small ROIs were grounded in the actual 1568x1063 screenshots.
    # Do not reuse them for another window geometry or capture without inspection.
    centers = []
    for x, y in [(287, 259), (1142, 259), (287, 895), (1142, 895)]:
        a = image[y-5:y+6, x-5:x+6].astype(float)
        weight = np.clip((a[:, :, 2]-a[:, :, 0])/185, 0, 1)
        weight = np.where(weight > .1, weight, 0)
        assert 10 <= weight.sum() <= 40, 'registration marker not identified'
        yy, xx = np.indices(weight.shape)
        centers.append([float((weight*(xx+x-5+.5)).sum()/weight.sum()),
                        float((weight*(yy+y-5+.5)).sum()/weight.sum())])
    sx = ((centers[1][0]-centers[0][0])+(centers[3][0]-centers[2][0]))/1560
    sy = ((centers[2][1]-centers[0][1])+(centers[3][1]-centers[1][1]))/1160
    ox = (centers[0][0]+centers[2][0])/2-10*sx
    oy = (centers[0][1]+centers[1][1])/2-10*sy
    assert 1 < sx < 1.2 and 1 < sy < 1.2 and abs(sx-sy) < .002
    known = [(10, 10), (790, 10), (10, 590), (790, 590)]
    residual = max(math.dist(c, (ox+x*sx, oy+y*sy)) for c, (x, y) in zip(centers, known))
    assert residual < .1
    return {'origin': [ox, oy], 'scale': [sx, sy], 'observedCenters': centers,
            'maxMarkerResidualPx': residual}


results = []
for fixture in read(ROOT/'probes.json'):
    name = fixture['name']
    document = read(fixture['request'])['document']
    result = read(ROOT/(name+'.response.json'))['result']
    screenshot = ROOT/('wps-'+name+'.png')
    image = np.array(Image.open(screenshot).convert('RGB'))
    assert image.shape == (1063, 1568, 3)
    # Inputs re-generated by the current exporter are byte-identical to the
    # original files that were actually opened in WPS and converted by LO.
    assert (ROOT/'observed-inputs'/(name+'.pptx')).read_bytes() == Path(fixture['pptx']).read_bytes()
    reg = registration(image)
    ox, oy = reg['origin']
    sx, sy = reg['scale']
    with fitz.open(ROOT/'libreoffice'/(Path(fixture['pptx']).stem+'.pdf')) as pdf:
        assert len(pdf) == 1 and abs(pdf[0].rect.width-600) < .01 and abs(pdf[0].rect.height-450) < .01
        drawings = [p for p in pdf[0].get_drawings() if p['fill'] and
                    max(abs(p['fill'][i]-[180, 40, 70][i]/255) for i in range(3)) < 1e-5]
    assert len(drawings) == 16
    cases = []
    for i, drawing in enumerate(drawings):
        expected = expected_vertices(result, document, 'shape:'+str(i))
        capture_expected = [(ox+x*sx, oy+y*sy) for x, y in expected]
        col, row = i % 4, i//4
        left, top = round(ox+col*200*sx), round(oy+row*150*sy)
        right, bottom = round(ox+(col+1)*200*sx), round(oy+(row+1)*150*sy)
        a = image[top:bottom, left:right].astype(float)
        alpha = (255-a[:, :, 1])/215
        color_error = np.max(np.abs(a-(255+(np.array([180, 40, 70])-255)*alpha[:, :, None])), axis=2)
        mask = (alpha >= .5) & (color_error < 25)
        assert 700 < np.count_nonzero(mask) < 8000
        assert not (mask[0].any() or mask[-1].any() or mask[:, 0].any() or mask[:, -1].any())
        edge = mask & ~(np.roll(mask, 1, 0) & np.roll(mask, -1, 0) & np.roll(mask, 1, 1) & np.roll(mask, -1, 1))
        yy, xx = np.nonzero(edge)
        pixels = [(float(x+left+.5), float(y+top+.5)) for x, y in zip(xx, yy)]
        wps_error = max(max(to_edge(p, capture_expected) for p in pixels),
                        max(min(math.dist(p, q) for q in pixels) for p in capture_expected))
        actual = []
        for item in drawing['items']:
            assert item[0] == 'l'
            for point in item[1:]:
                p = [point.x, point.y]
                if p not in actual:
                    actual.append(p)
        assert len(actual) == 4
        expected_pt = [[x*.75, y*.75] for x, y in expected]
        lo_error = max(max(to_edge(p, expected_pt) for p in actual),
                       max(to_edge(p, actual) for p in expected_pt))
        cases.append({'index': i, 'specification': fixture['cases'][i], 'expectedVerticesPx96': expected,
                      'wpsBoundaryPixelCount': len(pixels), 'wpsMaxBoundaryDistanceCapturePx': wps_error,
                      'wpsWithinCoarseObservationTolerance': wps_error <= 2.5,
                      'libreOfficeVerticesPt': actual, 'libreOfficeMaxVertexBoundaryDistancePt': lo_error,
                      'libreOfficeWithinObservationTolerance': lo_error <= .2})
    rgba = (ROOT/(name+'.rgba')).read_bytes()
    Image.frombytes('RGBA', (800, 600), rgba).save(ROOT/(name+'-kernel.png'))
    results.append({'name': name, 'source': entry(fixture['pptx']),
                    'placementResponse': entry(ROOT/(name+'.response.json')),
                    'privateCapture': entry(screenshot), 'registration': reg,
                    'pdf': entry(ROOT/'libreoffice'/(Path(fixture['pptx']).stem+'.pdf')), 'cases': cases})

with open('/Applications/wpsoffice.app/Contents/Info.plist', 'rb') as f:
    version = plistlib.load(f)['CFBundleShortVersionString']
report = {'format': 'musteroffice.group-placement-observations/1',
          'wpsVersion': version, 'libreOfficeVersion': '26.2.0.3 afbbd0df0edb6d40b450b0337ac646b0913a760c',
          'pdfExtractor': 'PyMuPDF '+fitz.VersionBind,
          'wpsObservationToleranceCapturePx': 2.5, 'libreOfficeObservationTolerancePt': .2,
          'scope': '48 owned asymmetric native path/group probes. WPS screen capture boundary measurement is coarse, contains resampling/compression and marker registration uncertainty, and is not a pixel fidelity or editing/round-trip gate. Full captures remain private; no user chrome is published.',
          'cases': results}
(ROOT/'observations.json').write_text(json.dumps(report, indent=2)+'\n')
all_cases = [c for page in results for c in page['cases']]
print(json.dumps({'probes': len(all_cases), 'wpsWithinCoarseTolerance': sum(c['wpsWithinCoarseObservationTolerance'] for c in all_cases),
                  'wpsMaxCapturePx': max(c['wpsMaxBoundaryDistanceCapturePx'] for c in all_cases),
                  'libreOfficeWithinTolerance': sum(c['libreOfficeWithinObservationTolerance'] for c in all_cases),
                  'libreOfficeMaxPt': max(c['libreOfficeMaxVertexBoundaryDistancePt'] for c in all_cases)}))
