"""Verify retained product commands, emitted SDK bytes and observed browser state.

This joins evidence; it does not run a browser or declare replacement acceptance.
Product source is never imported by this script.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def record(path, root):
    return dict(path=path.relative_to(root).as_posix(),
                bytes=path.stat().st_size, sha256=sha(path))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--product', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    core = Path(__file__).resolve().parents[2]
    product = args.product.resolve()
    stage = product / '.codex-work/integration/product-playback'
    checks, sources = [], {}
    for name, count in [('preparation-03', 18), ('client-03', 112),
                        ('viewer-03', 6), ('types-04', 0),
                        ('build-04', 0), ('desktop-build-01', 0)]:
        report_file, log_file = stage / (name + '.json'), stage / (name + '.log')
        report = json.loads(report_file.read_text())
        assert report['exitCode'] == 0 and report['sourceUnchanged']
        assert report['sourceBefore'] == report['sourceAfter']
        assert sha(log_file) == report['logSha256']
        for source, digest in report['sourceAfter'].items():
            assert sources.setdefault(source, digest) == digest, source
        log = log_file.read_text()
        if count:
            pattern = r'pass (\d+)' if name.startswith('preparation') else r'Tests\s+(\d+) passed'
            assert int(re.search(pattern, log)[1]) == count
            assert not re.search(r'[1-9]\d* skipped', log)
        checks.append(dict(run=name, passed=count, exitCode=0,
                           reportSha256=sha(report_file), logSha256=sha(log_file),
                           sourceInventoryMatches=True,
                           args=[value.replace(str(product), '$MUSTERWORK_WORKTREE')
                                 .replace(str(core), '$MUSTEROFFICE')
                                 for value in report['args']]))
    for source, digest in sources.items():
        assert sha(product / source) == digest, source

    pin = json.loads((product / 'components/musteroffice/playback-lock.json').read_text())['manifestSha256']
    package = product / 'components/musteroffice/generated/playback' / pin
    assert sha(package / 'bundle-manifest.json') == pin
    manifest = json.loads((package / 'bundle-manifest.json').read_text())
    assert manifest['releaseCleared'] is False
    selected = [entry for entry in manifest['files']
                if re.match(r'^(?:index\.mjs$|lib/|runtime/|notices/)', entry['path'])
                and (re.search(r'\.(?:js|mjs|wasm)$', entry['path'])
                     or entry['path'].startswith('notices/'))]
    builds = []
    for name in ['build-04', 'desktop-build-01']:
        folder = stage / name
        emitted = folder / 'musteroffice' / pin
        assert sorted(p.relative_to(emitted).as_posix() for p in emitted.rglob('*') if p.is_file()) == sorted(e['path'] for e in selected)
        for entry in selected:
            file = emitted / entry['path']
            assert sha(file) == entry['sha256'] and file.stat().st_size == entry['byteLength']
        workers = list((folder / 'assets').glob('office-playback-worker-*.js'))
        assert len(workers) == 1
        builds.append(dict(name=name, sdkFiles=len(selected),
                           sdkBytes=sum(e['byteLength'] for e in selected),
                           worker=record(workers[0], product),
                           files=[record(p, product) for p in sorted(folder.rglob('*')) if p.is_file()]))

    # Reference pixels were generated by Native in the previous recorded stage.
    previous_file = core / 'docs/reviews/evidence/2026-09-28-delivery-playback-verification.json'
    previous = json.loads(previous_file.read_text())
    frames = []
    for case in previous['parity']:
        if case['name'] not in ('product-v1', 'product-v2'):
            continue
        for index, frame in enumerate(case['frames']):
            file = core / '.codex-work/delivery-playback/parity-01' / case['name'] / f"page-{index // 2}-{frame['at']['ticks']}.rgba"
            assert sha(file) == frame['pixelsSha256']
            frames.append(dict(case=case['name'], **record(file, core)))
    assert len(frames) == 8

    browser = stage / 'browser'
    observations = {}
    for name in ['playing', 'paused', 'next', 'version', 'closed']:
        file = browser / ('built-csp-' + name + '.txt')
        content = file.read_text()
        stats = json.loads(re.search(r'\{"version"[^\n]+\}', content)[0])
        observations[name] = dict(stats=stats, evidence=record(file, product))
    playing, paused, next_page, version, closed = [observations[k]['stats'] for k in ['playing', 'paused', 'next', 'version', 'closed']]
    assert playing['frames'] == 1 and playing['workers'] == 1
    assert paused['frames'] > playing['frames'] and paused['lastFrame'] == playing['lastFrame']
    assert next_page['lastFrame'] != paused['lastFrame']
    assert playing['reads'] == paused['reads'] == next_page['reads'] == 15
    assert version['version'] == 1 and version['workers'] == version['terminated'] == 1
    assert closed['workers'] == closed['terminated'] == 2 and closed['frames'] > version['frames']
    assert json.loads((browser / 'built-csp-console.json').read_text()) == []
    csp = re.compile(r'<meta\s+http-equiv="Content-Security-Policy"[\s\S]*?>')
    expected_csp = csp.search((product / 'apps/desktop/index.html').read_text())[0]
    assert csp.search((browser / 'index.html').read_text())[0] == expected_csp
    # Vite preserves the actual policy content, while normalizing HTML whitespace.
    policy = re.search(r'content="([^"]+)"', expected_csp)[1]
    assert policy in (stage / 'build-04/index.html').read_text()
    assert policy in (stage / 'desktop-build-01/index.html').read_text()

    result = dict(version=1, date='2026-09-28', stage='product-playback',
                  status='Candidate product Worker and viewer integrated; full replacement incomplete',
                  tests=136, checks=checks, sourceInventory=sources,
                  package=dict(manifestSha256=pin, releaseCleared=False),
                  builds=builds, nativeReferenceFrames=frames,
                  previousDeliveryEvidenceSha256=sha(previous_file),
                  browser=dict(scope='Original product Vue components and Worker, owned loopback content transport, actual retained Agent Loop versions; not a complete authenticated Electron session',
                               observations=observations,
                               pageCspUnchanged=True,
                               consoleErrors=0,
                               screenshot=record(browser / 'built-csp-playing.png', product)),
                  developmentFailures=[
                      dict(problem='Slow frame followed by queued input could reverse sample time',
                           fix='Timestamp input on receipt, not when deferred work executes',
                           evidence=record(stage / 'clock-regression-before.log', product)),
                      dict(problem='Main-page WebAssembly.compile rejected by actual desktop CSP',
                           fix='Transfer verified code bytes and compile inside product Worker; page CSP unchanged',
                           evidence=record(browser / 'csp-before.txt', product)),
                      dict(problem='Owned harness initially used incorrect relative source path; initial preview port occupied',
                           fix='Correct harness path; use another loopback port without touching existing process')],
                  limitations=[
                      'Static owned two-page fixtures, synthetic fonts; no animation or visual quality acceptance',
                      'Eight product Worker frames matched prior Native pixels; not all-content or performance acceptance',
                      'Generic clicks only; navigation, object hit testing, resizing, audio/video and advanced content remain',
                      'One-time portable delivery packet is bounded at 128 MiB; no arbitrary-size claim',
                      'Browser termination invoked and stale results suppressed; no Worker exit acknowledgment',
                      'Desktop renderer build passed with existing chunk-size warnings; no complete Electron installer or live authenticated desktop acceptance',
                      'No stable engine/release switch; public release, Office/WPS, history, cross-platform, size and E0-E3 remain open'])
    with args.output.open('x') as stream:
        json.dump(result, stream, indent=2, ensure_ascii=False)
        stream.write('\n')
    print(json.dumps(dict(tests=result['tests'], sourceFiles=len(sources),
                          emittedSdkFiles=len(selected), emittedSdkBytes=builds[0]['sdkBytes'],
                          nativeFrames=len(frames), sha256=sha(args.output))))


if __name__ == '__main__':
    main()
