"""Owned native orientation cases for later target-application observations.
No screenshots or compatibility verdicts are generated by this script.
"""
import copy,hashlib,json,zipfile
from pathlib import Path
from lxml import etree as X
root=Path('.codex-work/stationary-gradient');out=root/'sources';out.mkdir(parents=True,exist_ok=True)
def entry(p):
    b=Path(p).read_bytes();return dict(path=str(p),byteLength=len(b),sha256=hashlib.sha256(b).hexdigest())
prior=json.loads(Path('.codex-work/radial-observation/sources.json').read_text())
seed=next(c['source'] for c in prior['cases'] if c['name']=='offset-ellipse');assert entry(seed['path'])==seed
ns={'a':'http://schemas.openxmlformats.org/drawingml/2006/main','p':'http://schemas.openxmlformats.org/presentationml/2006/main'}
parser=X.XMLParser(resolve_entities=False,no_network=True)
schema=X.XMLSchema(X.parse('.codex-work/ecma376/xsd/pml.xsd',parser))
records=[];parts=0
for kind in ['linear','rectangle','circle']:
    for variant,rotation,flip,group in [('plain',1800000,None,False),('quarter',5400000,None,False),
        ('horizontal-flip',1800000,'flipH',False),('vertical-flip',1800000,'flipV',False),('group',1800000,'flipH',True)]:
        for rotate in [False,True]:
            with zipfile.ZipFile(seed['path']) as z:data={n:z.read(n) for n in z.namelist()}
            page=X.fromstring(data['ppt/slides/slide1.xml'],parser);tree=page.find('p:cSld/p:spTree',ns)
            shape=tree.find('p:sp',ns);transform=shape.find('p:spPr/a:xfrm',ns);transform.set('rot',str(rotation))
            if flip:transform.set(flip,'1')
            fill=shape.find('p:spPr/a:gradFill',ns);fill.set('rotWithShape','1' if rotate else '0')
            old=fill.find('a:path',ns)
            if kind=='linear':
                at=list(fill).index(old);fill.remove(old);fill.insert(at,X.Element('{'+ns['a']+'}lin',ang='1800000',scaled='1'))
            else:old.set('path','circle' if kind=='circle' else 'rect')
            if group:
                wrapper=X.fromstring(f'<p:grpSp xmlns:p="{ns["p"]}" xmlns:a="{ns["a"]}"><p:nvGrpSpPr><p:cNvPr id="90" name="Owned orientation group"/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm rot="1200000" flipV="1"><a:off x="250000" y="200000"/><a:ext cx="1000000" cy="700000"/><a:chOff x="100000" y="100000"/><a:chExt cx="1300000" cy="1000000"/></a:xfrm></p:grpSpPr></p:grpSp>'.encode(),parser)
                index=list(tree).index(shape);tree.remove(shape);wrapper.append(shape);tree.insert(index,wrapper)
            name=f'{kind}-{variant}-'+('rotating' if rotate else 'stationary')
            shape.find('p:nvSpPr/p:cNvPr',ns).set('name','Owned orientation '+name)
            data['ppt/slides/slide1.xml']=X.tostring(page,xml_declaration=True,encoding='UTF-8',standalone=True)
            for n,b in data.items():
                if n.endswith('.xml'):
                    e=X.fromstring(b,parser);q=X.QName(e)
                    if q.namespace==ns['p'] and q.localname in ['presentation','sld','sldLayout','sldMaster']:schema.assertValid(e);parts+=1
            p=out/(name+'.pptx')
            with zipfile.ZipFile(p,'w',compression=zipfile.ZIP_DEFLATED) as z:
                for n,b in data.items():
                    info=zipfile.ZipInfo(n,(2026,9,26,0,0,0));info.compress_type=zipfile.ZIP_DEFLATED;z.writestr(info,b)
            records.append(dict(name=name,kind=kind,rotation=rotation,flip=flip,group=group,rotateWithShape=rotate,source=entry(p)))
(root/'inputs.json').write_text(json.dumps(dict(format='musteroffice.stationary-gradient-inputs/1',seed=seed,
    cases=records,officialXsdParts=parts,status='inputs-only; target observation awaits system permission',
    scope='30 original native PPTX files in 15 stationary/rotating pairs. Original grayscale stops and four magenta markers retained. No flattening, fonts or third-party content.'),indent=2)+'\n')
print(json.dumps(dict(cases=len(records),officialXsdParts=parts)))
