[package]
license.workspace = true
name = "mo-font"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
mo-common.workspace = true
mo-unicode.workspace = true
read-fonts.workspace = true
serde.workspace = true
schemars.workspace = true
sha2.workspace = true
thiserror.workspace = true

[lints]
workspace = true
