[package]
license.workspace = true
name = "mo-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
mo-common.workspace = true
mo-operation-service.workspace = true
mo-standard-host.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
mo-opc.workspace = true
mo-native-render.workspace = true

[lints]
workspace = true
