[package]
license.workspace = true
name = "mo-presentation-edit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
mo-common.workspace = true
mo-timeline.workspace = true
mo-unicode.workspace = true
mo-presentation-model.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
thiserror.workspace = true

[lints]
workspace = true
