[package]
license.workspace = true
name = "mo-kernel-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
mo-timeline.workspace = true
mo-image.workspace = true
mo-common.workspace = true
mo-charts.workspace = true
mo-geometry.workspace = true
mo-font.workspace = true
mo-text.workspace = true
mo-raster.workspace = true
mo-render.workspace = true
mo-presentation-compile.workspace = true
mo-presentation-delivery.workspace = true
mo-unicode.workspace = true
mo-opc.workspace = true
mo-xml.workspace = true
mo-pptx.workspace = true
mo-presentation-model.workspace = true
mo-presentation-edit.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true

[lints]
workspace = true
